apiVersion: v2
name: pipeline-pirates
description: A Helm chart for the Pipeline Pirates App
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 13.2.24
    repository: https://charts.bitnami.com/bitnami
    alias: pirates-db
    condition: pirates-db.enabled