apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  # Base64 encoding is handled automatically by Helm's b64enc function
  db-password: {{ "supersecretpassword" | b64enc | quote }}
  secret-key: {{ "your-super-secure-generated-key" | b64enc | quote }}
